source "http://rubygems.org"

gemspec

gem 'devise', '~> 2.0.0'
gem 'net-ldap', '~> 0.16.1'

group :test do
  gem 'ruby-debug', '>= 0.10.3', :platform => :mri_18
  gem 'debugger', :platform => :ruby_19
end
